/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface User {
  id: number;
  user_code: string;
  name: string;
  /** @nullable */
  name_kana: string | null;
  email: string;
  /** @nullable */
  email_verified_at: string | null;
  /** @nullable */
  phone: string | null;
  status: string;
  joined_at: string;
  /** @nullable */
  resigned_at: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}

export type AuthenticationExceptionResponse = {
  /** Error overview. */
  message: string;
};

export const getUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axios.get(
      `/user`,options
    );
  }

export type GetUserResult = AxiosResponse<User>
