/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Laravel
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface UserResource {
  id: number;
  user_code: string;
  name: string;
  /** @nullable */
  name_kana: string | null;
  email: string;
  /** @nullable */
  phone: string | null;
  status: string;
  joined_at: string;
  /** @nullable */
  resigned_at: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}

export type UserIndex200Links = {
  /** @nullable */
  first: string | null;
  /** @nullable */
  last: string | null;
  /** @nullable */
  prev: string | null;
  /** @nullable */
  next: string | null;
};

export type UserIndex200MetaLinksItem = {
  /** @nullable */
  url: string | null;
  label: string;
  active: boolean;
};

export type UserIndex200Meta = {
  /** @minimum 1 */
  current_page: number;
  /**
   * @minimum 1
   * @nullable
   */
  from: number | null;
  /** @minimum 1 */
  last_page: number;
  /** Generated paginator links. */
  links: UserIndex200MetaLinksItem[];
  /**
   * Base path for paginator generated URLs.
   * @nullable
   */
  path: string | null;
  /**
   * Number of items shown per page.
   * @minimum 0
   */
  per_page: number;
  /**
   * Number of the last item in the slice.
   * @minimum 1
   * @nullable
   */
  to: number | null;
  /**
   * Total number of items being paginated.
   * @minimum 0
   */
  total: number;
};

export type UserIndex200 = {
  data: UserResource[];
  links: UserIndex200Links;
  meta: UserIndex200Meta;
};

/**
 * @summary Display a listing of the resource
 */
export const userIndex = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserIndex200>> => {
    return axios.get(
      `/user`,options
    );
  }

export type UserIndexResult = AxiosResponse<UserIndex200>
