/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sales-management-system
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './custom-instance';
export interface UserResource {
  id: number;
  user_code: string;
  name: string;
  email: string;
  status: string;
  roles: string | string[];
}

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};

export type ValidationExceptionResponse = {
  /** Errors overview. */
  message: string;
  /** A detailed description of each field that failed validation. */
  errors: ValidationExceptionResponseErrors;
};

export type UserIndexParams = {
/**
 * 名前、よみがな
 */
keyword?: string;
userCode?: string;
/**
 * メールアドレス
 */
email?: string;
/**
 * trueの場合、在職者のみ取得する
 */
activeOnly?: string;
/**
 * 役職者
 */
role?: string;
};

export type UserIndex200 = {
  data: UserResource[];
};

/**
 * @summary Display a listing of the resource
 */
export const userIndex = (
    params?: UserIndexParams,
 ) => {
      return customInstance<UserIndex200>(
      {url: `/user`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Store a newly created resource in storage
 */
export const userStore = (
    
 ) => {
      return customInstance<void>(
      {url: `/user`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Display the specified resource
 */
export const userShow = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update the specified resource in storage
 */
export const userUpdate = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Remove the specified resource from storage
 */
export const userDestroy = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'DELETE'
    },
      );
    }
  
export type UserIndexResult = NonNullable<Awaited<ReturnType<typeof userIndex>>>
export type UserStoreResult = NonNullable<Awaited<ReturnType<typeof userStore>>>
export type UserShowResult = NonNullable<Awaited<ReturnType<typeof userShow>>>
export type UserUpdateResult = NonNullable<Awaited<ReturnType<typeof userUpdate>>>
export type UserDestroyResult = NonNullable<Awaited<ReturnType<typeof userDestroy>>>
