/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sales-management-system
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './custom-instance';
export interface UserResource {
  /** ユーザーコード システム内で一意となる識別子です。 */
  user_code: number;
  /** ユーザー名 画面上に表示する氏名です。 */
  name: string;
  /**
   * ユーザー名(かな) 画面上に表示する氏名のよみがなです。
   * @nullable
   */
  name_kana: string | null;
  /** メールアドレス ログインおよび通知に利用します。 */
  email: string;
  /** 在籍状態 値の意味：
- active : 在職中
- leave : 休職中
- resigned : 退職済 */
  status: string;
  /** 保有権限一覧 ユーザーに付与されている権限です。

値の例：
- admin
- office_worker
- sales */
  roles: string[];
}

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};

export type ValidationExceptionResponse = {
  /** Errors overview. */
  message: string;
  /** A detailed description of each field that failed validation. */
  errors: ValidationExceptionResponseErrors;
};

export type UserIndexParams = {
/**
 * ユーザー名またはユーザー名（かな）で検索します。 部分一致検索を行います。
名前・よみがなのいずれかに一致するユーザーを取得します。

検索例：
- "田中" → 「田中太郎」「田中一郎」
- "たなか" → 「たなかたろう」
- "太郎" → 「山田太郎」
 */
keyword?: string;
/**
 * ユーザーIDで検索します。 完全一致検索を行います。
ユーザーIDを指定してください。

検索例：
- 1
- 22
 */
userCode?: string;
/**
 * メールアドレスで検索します。 完全一致検索を行います。
指定したメールアドレスを持つユーザーを取得します。

検索例：
- tanaka@example.com
- yamada@example.com
 */
email?: string;
/**
 * 在職者のみを取得するかを指定します。 true を指定した場合は在職中(status:active)のユーザーのみ取得します。
false の場合は退職者、休職者を含む全ユーザーを取得します。

API仕様上は文字列として受け取ります。

指定例：
- true
- false
 */
activeOnly?: string;
/**
 * ロールIDで検索します。 完全一致検索を行います。
指定したロールIDを持つユーザーのみ取得します。

ロールIDは roles テーブルの主キーを指定してください。

指定例：
- 1 : システム管理者
- 2 : 事務担当
- 3 : 営業担当
 */
role_id?: number;
};

export type UserIndex200 = {
  data: UserResource[];
};

/**
 * @summary Display a listing of the resource
 */
export const userIndex = (
    params?: UserIndexParams,
 ) => {
      return customInstance<UserIndex200>(
      {url: `/user`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Store a newly created resource in storage
 */
export const userStore = (
    
 ) => {
      return customInstance<void>(
      {url: `/user`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Display the specified resource
 */
export const userShow = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update the specified resource in storage
 */
export const userUpdate = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Remove the specified resource from storage
 */
export const userDestroy = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/user/${id}`, method: 'DELETE'
    },
      );
    }
  
export type UserIndexResult = NonNullable<Awaited<ReturnType<typeof userIndex>>>
export type UserStoreResult = NonNullable<Awaited<ReturnType<typeof userStore>>>
export type UserShowResult = NonNullable<Awaited<ReturnType<typeof userShow>>>
export type UserUpdateResult = NonNullable<Awaited<ReturnType<typeof userUpdate>>>
export type UserDestroyResult = NonNullable<Awaited<ReturnType<typeof userDestroy>>>
