/**
 * Generated by orval 🍺
 * Do not edit manually.
 * sales-management-system
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './custom-instance';
export interface PasswordSetupRequest {
  /**
     * 初期パスワード設定用のトークンを指定します。 ユーザー登録時に発行された初期パスワード設定用の
     * トークンを指定してください。
     */
  token: string;
  /**
     * メールアドレスを指定します。 初期パスワードを設定するユーザーの
     * メールアドレスを指定してください。
     */
  email: string;
  /**
     * パスワードを指定します。 初期パスワードを設定するユーザーの
     * パスワードを指定してください。
     */
  password: string;
  /** 確認用パスワードを指定します。 passwordと同じ値を指定してください。 */
  password_confirmation: string;
}

export interface RoleResource {
  /**
     * 役割ID roles テーブルの主キーです。
     * 役割を一意に識別するためのIDです。
     *
     * 指定例：
     * - 1 : システム管理者
     * - 2 : 事務
     * - 3 : 営業
     */
  id: number;
  /**
     * 役割名 利用可能な役割の名称です。
     * 検索画面のユーザー情報の表示などに利用します。
     *
     * 値の例：
     * - システム管理者
     * - 事務
     * - 営業
     */
  name: string;
}

export interface UserResource {
  /**
     * ユーザーコード システム内で一意となる識別子です。
     * 形式は「E + 3桁の数字」です。
     */
  userCode: string;
  /** ユーザー名 画面上に表示する氏名です。 */
  name: string;
  /**
     * ユーザー名(かな) 画面上に表示する氏名のよみがなです。
     * @nullable
     */
  nameKana: string | null;
  /** メールアドレス ログインおよび通知に利用します。 */
  email: string;
  /**
     * 在籍状態 値の意味：
     * - active : 在職中
     * - leave : 休職中
     * - resigned : 退職済
     */
  status: string;
  /**
     * 保有権限一覧 ユーザーに付与されている権限です。
     *
     * 値の例：
     * - admin
     * - office_worker
     * - sales
     */
  roles: string[];
}

export interface UserStoreRequest {
  /**
     * ユーザーコードを指定します。 新規登録するユーザーのユーザーコードを指定してください。
     * 「E + 3桁の数字」で指定します。
     * すでに登録されているユーザーコードは使用できません。
     *
     * 入力例：
     * - E001
     * - E022
     * @pattern ^E\d{3}$
     */
  userCode: string;
  /**
     * ユーザー名を指定します。 新規登録するユーザーのユーザー名を指定してください。
     *
     * 入力例：
     * - 田中 太郎
     * - 山田 花子
     */
  name: string;
  /**
     * ユーザー名のよみがなを指定します。 新規登録するユーザーのユーザー名のよみがなを指定してください。
     * 必要がない場合は省略できます。
     *
     * 入力例：
     * - たなか たろう
     * - やまだ はなこ
     * @nullable
     */
  name_kana?: string | null;
  /**
     * メールアドレスを指定します。 新規登録するユーザーのメールアドレスを指定してください。
     * すでに登録されているメールアドレスは使用できません。
     * RFCに準拠したメールアドレス形式で、ドメインがDNS上に存在する必要があります。
     *
     * 入力例：
     * - tanaka@example.com
     * - yamada@example.com
     */
  email: string;
  /**
     * 電話番号を指定します。 新規登録するユーザーの電話番号を指定してください。
     * 最大20文字の登録ができます。
     * 電話番号がない場合は省略できます。
     *
     * 入力例：
     * - 090-123-456
     * @maxLength 20
     * @nullable
     */
  phone?: string | null;
  /**
     * 役職を指定します。 新規登録するユーザーの役職を指定してください。
     * 役職がない場合は省略できます。
     *
     * 入力例：
     * - 課長
     * @nullable
     */
  position?: string | null;
  /**
     * 入社日を指定します。 新規登録するユーザーの入社日を指定してください。
     * YYYY-MM-DD形式で入力します。
     *
     * 入力例：
     * - 2026-04-01
     */
  joined_at: string;
  /**
     * 役割IDを指定します。 新規登録するユーザーの役割IDを指定してください。
     *
     * 役割IDは roles テーブルの主キーを指定してください。
     *
     * 指定例：
     * - 1 : システム管理者
     * - 2 : 事務担当
     * - 3 : 営業担当
     */
  roleId: string;
}

/**
 * 雇用状態を指定します。 更新するユーザーの現在の雇用状態を指定してください。
 *
 * 指定可能な値：
 * - active: 在職
 * - leave: 休職
 * - resigned: 退職
 */
export type UserUpdateRequestStatus = typeof UserUpdateRequestStatus[keyof typeof UserUpdateRequestStatus];


export const UserUpdateRequestStatus = {
  active: 'active',
  leave: 'leave',
  resigned: 'resigned',
} as const;

export interface UserUpdateRequest {
  /**
     * ユーザーコードを指定します。 更新するユーザーのユーザーコードを指定してください。
     * 「E + 3桁の数字」で指定します。
     * すでに登録されているユーザーコードは使用できません。
     * ただし更新するユーザー自身のユーザーコードは対象から外します。
     *
     * 入力例：
     * - E001
     * - E022
     * @pattern ^E\d{3}$
     */
  userCode: string;
  /**
     * ユーザー名を指定します。 更新するユーザーのユーザー名を指定してください。
     *
     * 入力例：
     * - 田中 太郎
     * - 山田 花子
     */
  name: string;
  /**
     * ユーザー名のよみがなを指定します。 更新するユーザーのユーザー名のよみがなを指定してください。
     * 必要がない場合は省略できます。
     *
     * 入力例：
     * - たなか たろう
     * - やまだ はなこ
     * @nullable
     */
  name_kana?: string | null;
  /**
     * メールアドレスを指定します。 更新するユーザーのメールアドレスを指定してください。
     * すでに登録されているメールアドレスに更新できません。
     * ただし更新するユーザー自身のメールアドレスは対象から外します。
     * RFCに準拠したメールアドレス形式で、ドメインがDNS上に存在する必要があります。
     *
     * 入力例：
     * - tanaka@example.com
     * - yamada@example.com
     */
  email: string;
  /**
     * 電話番号を指定します。 更新するユーザーの電話番号を指定してください。
     * 最大20文字の登録ができます。
     * 電話番号がない場合は省略できます。
     *
     * 入力例：
     * - 090-123-456
     * @maxLength 20
     * @nullable
     */
  phone?: string | null;
  /**
     * 役職を指定します。 更新するユーザーの役職を指定してください。
     * 役職がない場合は省略できます。
     *
     * 入力例：
     * - 課長
     * @nullable
     */
  position?: string | null;
  /**
     * 雇用状態を指定します。 更新するユーザーの現在の雇用状態を指定してください。
     *
     * 指定可能な値：
     * - active: 在職
     * - leave: 休職
     * - resigned: 退職
     */
  status: UserUpdateRequestStatus;
  /**
     * 入社日を指定します。 更新するユーザーの入社日を指定してください。
     * YYYY-MM-DD形式で入力します。
     *
     * 入力例：
     * - 2026-04-01
     */
  joined_at: string;
  /**
     * 退職日を指定します。 更新するユーザーの退職日を指定してください。
     * YYYY-MM-DD形式で入力します。
     * 退職していない場合はnullを指定できます。
     *
     * 入力例：
     * - 2026-09-30
     * @nullable
     */
  resigned_at?: string | null;
  /**
     * 役割IDを指定します。 更新するユーザーの役割IDを指定してください。
     *
     * 役割IDは roles テーブルの主キーを指定してください。
     *
     * 指定例：
     * - 1 : システム管理者
     * - 2 : 事務担当
     * - 3 : 営業担当
     */
  roleId: string;
}

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};

export type ValidationExceptionResponse = {
  /** Errors overview. */
  message: string;
  /** A detailed description of each field that failed validation. */
  errors: ValidationExceptionResponseErrors;
};

export type ModelNotFoundExceptionResponse = {
  /** Error overview. */
  message: string;
};

export type RolesIndex200 = {
  data: RoleResource[];
};

export type UserIndexParams = {
/**
 * ユーザー名またはユーザー名（かな）で検索します。 部分一致検索を行います。
 * 名前・よみがなのいずれかに一致するユーザーを取得します。
 *
 * 検索例：
 * - "田中" → 「田中太郎」「田中一郎」
 * - "たなか" → 「たなかたろう」
 * - "太郎" → 「山田太郎」
 */
keyword?: string;
/**
 * ユーザーコードで検索します。 完全一致検索を行います。
 * ユーザーコードを指定してください。
 *
 * 検索例：
 * - 1
 * - 22
 */
userCode?: string;
/**
 * メールアドレスで検索します。 完全一致検索を行います。
 * 指定したメールアドレスを持つユーザーを取得します。
 *
 * 検索例：
 * - tanaka@example.com
 * - yamada@example.com
 */
email?: string;
/**
 * 在職者のみを取得するかを指定します。 true を指定した場合は在職中(status:active)のユーザーのみ取得します。
 * false の場合は退職者、休職者を含む全ユーザーを取得します。
 *
 * API仕様上は文字列として受け取ります。
 *
 * 指定例：
 * - true
 * - false
 */
activeOnly?: string;
/**
 * 役割IDで検索します。 完全一致検索を行います。
 * 指定した役割IDを持つユーザーのみ取得します。
 *
 * 役割IDは roles テーブルの主キーを指定してください。
 *
 * 指定例：
 * - 1 : システム管理者
 * - 2 : 事務担当
 * - 3 : 営業担当
 */
roleId?: string;
/**
 * ページ番号を指定します。 ページネーションされた一覧データの取得対象ページを指定します。
 * 指定しない場合は1ページ目を取得します。
 *
 * 1ページあたりの取得件数はサーバー側で設定された件数に従います。
 *
 * 指定例：
 * - 1 : 1ページ目を取得
 * - 2 : 2ページ目を取得
 * - 3 : 3ページ目を取得
 *
 * リクエスト例：
 * - /api/user?page=1
 * - /api/user?page=2
 */
page?: string;
};

export type UserIndex200Links = {
  /** @nullable */
  first: string | null;
  /** @nullable */
  last: string | null;
  /** @nullable */
  prev: string | null;
  /** @nullable */
  next: string | null;
};

export type UserIndex200MetaLinksItem = {
  /** @nullable */
  url: string | null;
  label: string;
  active: boolean;
};

export type UserIndex200Meta = {
  /** @minimum 1 */
  current_page: number;
  /**
     * @minimum 1
     * @nullable
     */
  from: number | null;
  /** @minimum 1 */
  last_page: number;
  /** Generated paginator links. */
  links: UserIndex200MetaLinksItem[];
  /**
     * Base path for paginator generated URLs.
     * @nullable
     */
  path: string | null;
  /**
     * Number of items shown per page.
     * @minimum 0
     */
  per_page: number;
  /**
     * Number of the last item in the slice.
     * @minimum 1
     * @nullable
     */
  to: number | null;
  /**
     * Total number of items being paginated.
     * @minimum 0
     */
  total: number;
};

export type UserIndex200 = {
  data: UserResource[];
  links: UserIndex200Links;
  meta: UserIndex200Meta;
};

export type UserStore201 = {
  data: UserResource;
};

export type UserShow200 = {
  data: UserResource;
};

export type UserUpdate200 = {
  data: UserResource;
};

export const rolesIndex = (

 ) => {
      return customInstance<RolesIndex200>(
      {url: `/roles`, method: 'GET'
    },
      );
    }

/**
 * @summary Display a listing of the resource
 */
export const userIndex = (
    params?: UserIndexParams,
 ) => {
      return customInstance<UserIndex200>(
      {url: `/user`, method: 'GET',
        params
    },
      );
    }

/**
 * @summary Store a newly created resource in storage
 */
export const userStore = (
    userStoreRequest: UserStoreRequest,
 ) => {
      return customInstance<UserStore201>(
      {url: `/user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userStoreRequest
    },
      );
    }

/**
 * @summary Display the specified resource
 */
export const userShow = (
    user: number,
 ) => {
      return customInstance<UserShow200>(
      {url: `/user/${user}`, method: 'GET'
    },
      );
    }

/**
 * @summary Update the specified resource in storage
 */
export const userUpdate = (
    user: number,
    userUpdateRequest: UserUpdateRequest,
 ) => {
      return customInstance<UserUpdate200>(
      {url: `/user/${user}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest
    },
      );
    }

/**
 * @summary Remove the specified resource from storage
 */
export const userDestroy = (
    user: number,
 ) => {
      return customInstance<void>(
      {url: `/user/${user}`, method: 'DELETE'
    },
      );
    }

export const userSetupPassword = (
    passwordSetupRequest: PasswordSetupRequest,
 ) => {
      return customInstance<void>(
      {url: `/password/setup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordSetupRequest
    },
      );
    }

export type RolesIndexResult = NonNullable<Awaited<ReturnType<typeof rolesIndex>>>
export type UserIndexResult = NonNullable<Awaited<ReturnType<typeof userIndex>>>
export type UserStoreResult = NonNullable<Awaited<ReturnType<typeof userStore>>>
export type UserShowResult = NonNullable<Awaited<ReturnType<typeof userShow>>>
export type UserUpdateResult = NonNullable<Awaited<ReturnType<typeof userUpdate>>>
export type UserDestroyResult = NonNullable<Awaited<ReturnType<typeof userDestroy>>>
export type UserSetupPasswordResult = NonNullable<Awaited<ReturnType<typeof userSetupPassword>>>
